CREATE OR REPLACE STREAM "testeapp" (
    NOME_ESTACAO_MAX VARCHAR(16),
    NOME_ESTACAO_MIN VARCHAR(16),
    LATITUDE_MIN DOUBLE,
    LONGITUDE_MIN DOUBLE,
    LATITUDE_MAX DOUBLE,
    LONGITUDE_MAX DOUBLE,
    HORAMEDICAO INTEGER,
    TEMPERATURA_MIM REAL,
    CODIGO_ESTACAO_MAX VARCHAR(4),
    TEMPERATURA_MAX REAL, 
    CODIGO_ESTACAO_MIN VARCHAR(4),
    UMIDADE_RELATIVA INTEGER,
    PRECIPITACAO_TOTAL DOUBLE,
    RADIACAO_GLOBAL DOUBLE);

CREATE OR REPLACE PUMP "REFERENCE_STREAM_PUMP" AS INSERT INTO "testeapp"
SELECT NOME_ESTACAO_MAX, NOME_ESTACAO_MIN,LATITUDE_MIN,LONGITUDE_MIN,LATITUDE_MAX,LONGITUDE_MAX, c.HORAMEDICAO, TEMPERATURA_MIM, CODIGO_ESTACAO_MAX, TEMPERATURA_MAX, CODIGO_ESTACAO_MIN, UMIDADE_RELATIVA, PRECIPITACAO_TOTAL, RADIACAO_GLOBAL FROM 
    (SELECT  a.NOME_ESTACAO NOME_ESTACAO_MIN,a.LATITUDE LATITUDE_MIN, a.LONGITUDE LONGITUDE_MIN, a.HORAMEDICAO, b.TEMPERATURA_MIM, a.CODIGO_ESTACAO CODIGO_ESTACAO_MIN,  b.UMIDADE_RELATIVA, b.PRECIPITACAO_TOTAL, b.RADIACAO_GLOBAL
        FROM "SOURCE_SQL_STREAM_001" a
        RIGHT JOIN (
            SELECT STREAM HORAMEDICAO, MIN(TEMPERATURA_MIM) TEMPERATURA_MIM, SUM(RADIACAO_GLOBAL) RADIACAO_GLOBAL, SUM(PRECIPITACAO_TOTAL) PRECIPITACAO_TOTAL, AVG(UMIDADE_RELATIVA) UMIDADE_RELATIVA
                FROM "SOURCE_SQL_STREAM_001"
                GROUP BY HORAMEDICAO,
                STEP("SOURCE_SQL_STREAM_001".ROWTIME BY INTERVAL '1' MINUTE)
        ) b ON a.TEMPERATURA_MIM = b.TEMPERATURA_MIM
    ) c 
    JOIN
    (SELECT  d.HORAMEDICAO, e.TEMPERATURA_MAX, d.CODIGO_ESTACAO CODIGO_ESTACAO_MAX, d.NOME_ESTACAO NOME_ESTACAO_MAX, d.LATITUDE LATITUDE_MAX, d.LONGITUDE LONGITUDE_MAX
        FROM "SOURCE_SQL_STREAM_001" d
        RIGHT JOIN (
            SELECT STREAM HORAMEDICAO, MAX(TEMPERATURA_MAX) TEMPERATURA_MAX
            FROM "SOURCE_SQL_STREAM_001"
            GROUP BY HORAMEDICAO,
            STEP("SOURCE_SQL_STREAM_001".ROWTIME BY INTERVAL '1' MINUTE)
        ) e ON d.TEMPERATURA_MAX = e.TEMPERATURA_MAX) f 
    ON c.HORAMEDICAO = f.HORAMEDICAO;